vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
